version: '3.4'
services:
  app:
    build: .
    ports:
      - "9091:9091"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customer_api
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer_api
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: