server:
  port: 9091
spring:
  application:
    name: customer-api
  data:
    mongodb:
      uuid-representation: standard
      uri: mongodb://tastefood:12345678@docdb-2024-12-04-23-03-34.cluster-clc2ku84ap6h.us-east-1.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      database: "taste-food"