server:
  port: 9091
spring:
  application:
    name: customer-api
  data:
    mongodb:
      uuid-representation: standard
      uri: mongodb://taste_food:HtP3FSQuzk6KYpmdgfeZb5@default.cluster-clc2ku84ap6h.us-east-1.docdb.amazonaws.com:27017/?tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      database: "taste-food"